service: space-ship-generator
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - "*"
      maxAge: 86400
  environment:
    NODE_OPTIONS: --enable-source-maps
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    SPACE_SHIP_BUCKET: space-ship-sprites
    # Allow override via env var at deploy time; falls back to service-stage default
    SCOREBOARD_TABLE: ${env:SCOREBOARD_TABLE, '${self:service}-scoreboard-${sls:stage}'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:HeadObject
          Resource: arn:aws:s3:::space-ship-sprites/*
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:DescribeTable
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.SCOREBOARD_TABLE}

functions:
  generateSpaceShip:
    # Set function timeout to 29 seconds (max for API Gateway synchronous invocations)
    timeout: 29
    handler: src/handler.generateSpaceShipHandler
    events:
      - httpApi:
          path: /generate-space-ship
          method: post
  generateSpriteSheet:
    timeout: 29
    handler: src/handler.generateSpriteSheetHandler
    events:
      - httpApi:
          path: /generate-sprite-sheet
          method: post
  diffBoundingBox:
    timeout: 29
    handler: src/handler.diffBoundingBoxHandler
    events:
      - httpApi:
          path: /diff-bounding-box
          method: post
  resize:
    timeout: 29
    handler: src/handler.resizeHandler
    events:
      - httpApi:
          path: /resize
          method: post
  nameShip:
    timeout: 15
    handler: src/handler.nameShipHandler
    events:
      - httpApi:
          path: /name-ship
          method: post
  updateScoreboard:
    timeout: 10
    handler: src/handler.updateScoreboardHandler
    events:
      - httpApi:
          path: /scoreboard
          method: post
  listScoreboard:
    timeout: 10
    handler: src/handler.listScoreboardHandler
    events:
      - httpApi:
          path: /scoreboard
          method: get

plugins:
  - serverless-offline

package:
  patterns:
    # Include entire assets directory (example_1.png .. example_3.png and any future images)
    - assets/**

resources:
  # Intentionally empty: DynamoDB table is managed manually outside CloudFormation
