service: space-ship-generator
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_OPTIONS: --enable-source-maps

functions:
  generateSpaceShip:
    handler: src/handler.generateSpaceShip
    events:
      - httpApi:
          path: /generate-space-ship
          method: post

plugins:
  - serverless-offline
