service: space-ship-generator
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - https://benlirio.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - OPTIONS
        - GET
        - POST
      maxAge: 86400
  environment:
    NODE_OPTIONS: --enable-source-maps
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    SPACE_SHIP_BUCKET: space-ship-sprites
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:HeadObject
          Resource: arn:aws:s3:::space-ship-sprites/*

functions:
  generateSpaceShip:
    # Set function timeout to 29 seconds (max for API Gateway synchronous invocations)
    timeout: 29
    handler: src/handler.generateSpaceShip
    events:
      - httpApi:
          path: /generate-space-ship
          method: post

plugins:
  - serverless-offline

package:
  patterns:
    # Include entire assets directory (example_1.png .. example_3.png and any future images)
    - assets/**
